# Generated by Django 4.0.4 on 2022-07-13 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resortapp', '0002_attendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='date_arrival',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='date_vaccate',
            field=models.DateField(),
        ),
    ]
