# Generated by Django 4.0.4 on 2022-07-13 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resortapp', '0003_alter_booking_booking_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='photo',
            field=models.FileField(default=2, upload_to=''),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='menubooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_date', models.DateField()),
                ('quantity', models.BigIntegerField()),
                ('menu_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resortapp.menu')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resortapp.registration')),
            ],
        ),
    ]
