# Generated by Django 4.0.4 on 2022-07-14 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resortapp', '0005_remove_menu_cottage_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='menu_order_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.BigIntegerField()),
                ('status', models.CharField(max_length=30)),
                ('menu_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resortapp.menu')),
            ],
        ),
        migrations.CreateModel(
            name='menu_orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_date', models.DateField()),
                ('total_amount', models.BigIntegerField()),
                ('status', models.CharField(max_length=30)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resortapp.registration')),
            ],
        ),
        migrations.DeleteModel(
            name='menubooking',
        ),
        migrations.AddField(
            model_name='menu_order_details',
            name='menu_orderid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resortapp.menu_orders'),
        ),
    ]
