# Generated by Django 4.0.4 on 2022-07-15 11:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('resortapp', '0007_bank'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='todate',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
