# Generated by Django 4.0.4 on 2022-07-18 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resortapp', '0009_booking_total_amount_alter_package_end_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offers',
            name='rate',
        ),
    ]
