# Generated by Django 4.0.4 on 2022-07-20 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resortapp', '0010_remove_offers_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='status',
            field=models.CharField(default=11, max_length=50),
            preserve_default=False,
        ),
    ]
